##########################################
############  Core Properties ############
##########################################
application:
  tenant:
    id: service-auth-dev

spring:
##########################################
########## Database Properties ###########
##########################################
#  datasource:
#    password: secureqr@!$001
#    url: jdbc:mysql://34.125.26.105:3306/${application.tenant.id}
#    username: ${application.tenant.id}

##########################################
########## Logging Properties ###########
##########################################
logging:
  config: classpath:logback-spring-json.xml