##########################################
############  Core Properties ############
##########################################
application:
  tenant:
    id: service-auth-local
server:
  port: 8080
spring:
  application:
    name: service-auth
##########################################
########## Database Properties ###########
##########################################
  datasource:
    password: ${application.tenant.id}
    url: jdbc:mysql://localhost:3306/${application.tenant.id}?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baselineOnMigrate: true
    schemas: ${application.tenant.id}
    default-schema: ${application.tenant.id}
    placeholders:
      dbuser: ${application.tenant.id}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
        time_zone: UTC
        default_schema: '[${application.tenant.id}]'
  servlet:
    multipart:
      max-file-size: 20KB

##########################################
########## Logging Properties ###########
##########################################
logging:
  config: classpath:logback-spring.xml
  level:
    ROOT: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    tech.sarthee.auth: DEBUG
##########################################
########## File Properties ###########
##########################################
file:
  storage:
    path: